[GLOBAL]
pants_version = "2.24.1"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.isort",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.shell",
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["==3.9.*"]
enable_resolves = true
pip_version = "latest"

[python-infer]
unowned_dependency_behavior = "error"
